# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 7
    wait_for_ci: yes

coverage:
  precision: 4
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: auto
        threshold: 3%
        base: auto
        flags:
          - unit
        paths:
          - "src"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

comment:
  branches:
    - main
    - *
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
