# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 5
  round: down
  range: "75...90"
  status:
    project:
      default:
        target: auto
        threshold: 3%
        flags:
          - unit
        paths:
          - src
    patch:
      default:
        target: 50%
        threshold: 3%
        flags:
          - unit
        paths:
          - src

flag_management:
  individual_flags:
    - name: unit
      paths:
        - src/
      after_n_builds: 9
    - name: valgrind
      paths:
        - src/
      after_n_builds: 5

comment:
  layout: "header, reach, diff, files, flags"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
