# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 1
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot
    commit-message:
      prefix: "chore(deps)"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot
    commit-message:
      prefix: "chore(ci)"
      include: scope
