FROM amd64/ubuntu:18.04
COPY . /ngx_wasm_module

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        ninja-build \
        python3 \
        cmake \
        gcc-8 \
        libstdc++-8-dev \
        git \
        openssh-server \
        openssh-clients \
        pkg-config \
        libglib2.0-dev \
        clang \
        curl

# Install CMake >= 3.12 (required by wabt-sys,
# which is required by cwabt, used by the V8 backend).
RUN apt-get install -y --no-install-recommends \
        python3-pip \
        python3-setuptools && \
        pip3 install --upgrade pip && \
        pip3 install scikit-build && \
        pip3 install cmake

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:$PATH
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME $RUSTUP_HOME
