FROM amd64/archlinux:latest
COPY . /ngx_wasm_module

RUN pacman -Syyu --noconfirm \
    cmake \
    clang \
    make \
    gcc \
    python \
    git \
    pkg-config \
    which \
    ninja

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:$PATH
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME $RUSTUP_HOME
