FROM amd64/ubuntu:20.04
COPY . /ngx_wasm_module

ARG GOLANG_VERSION=1.19.5
ARG TINYGO_VERSION=0.26.0
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        build-essential \
        ninja-build \
        python3 \
        cmake \
        gcc-10 \
        libstdc++-10-dev \
        git \
        pkg-config \
        libglib2.0-dev \
        clang \
        curl

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:$PATH
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME $RUSTUP_HOME

# Note: this image is also used for local CI runs
RUN apt-get install -y \
        clang-tools \
        libpcre3-dev \
        libssl-dev \
        zlib1g-dev \
        valgrind \
        nodejs \
        gcovr \
        sudo && \
    curl -sLO https://golang.google.cn/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    curl -sLO https://github.com/tinygo-org/tinygo/releases/download/v$TINYGO_VERSION/tinygo_${TINYGO_VERSION}_amd64.deb && \
    dpkg -i tinygo_${TINYGO_VERSION}_amd64.deb
ENV PATH $PATH:/usr/local/go/bin
