FROM amd64/ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        gcc \
        clang \
        curl \
        && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
