FROM ubuntu:20.04
COPY . /ngx_wasm_module

ARG GOLANG_VERSION=1.19.5
ARG TINYGO_VERSION=0.27.0
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        build-essential \
        ninja-build \
        python3 \
        cmake \
        gcc-10 \
        libstdc++-10-dev \
        git \
        pkg-config \
        libglib2.0-dev \
        clang \
        curl \
        binfmt-support \
        qemu-user-static

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:$PATH
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME $RUSTUP_HOME
