FROM amd64/ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        clang \
        gcc \
        curl

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:$PATH
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME

# Note: this image is also used for local CI runs
RUN apt-get install -y --no-install-recommends \
        libpcre3-dev \
        zlib1g-dev \
        clang-tools \
        valgrind \
        nodejs \
        gcovr \
        sudo \
        git
