FROM amd64/centos:7

RUN yum update -y && yum install -y \
    gcc \
    clang \
    perl \
    make \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable

# bypass "multiple definitions of 'assertions'" linker error from wasm.h:
# https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h#L29
ENV LD_FLAGS="-Wl,--allow-multiple-definition"
