FROM amd64/centos:8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-* && \
    yum upgrade -y && \
    yum install -y \
        gcc \
        clang \
        perl \
        make \
        && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
