#ifndef _NGX_PROXY_WASM_H_INCLUDED_
#define _NGX_PROXY_WASM_H_INCLUDED_


#include <ngx_core.h>


typedef enum {
    NGX_PROXY_WASM_0_1_0,
    NGX_PROXY_WASM_0_2_0,
    NGX_PROXY_WASM_0_2_1
} ngx_proxy_wasm_abi_version;


//typedef enum {
//    NGX_PROXY_WASM_OK = 0,
//    NGX_PROXY_WASM_BAD_VM,
//    NGX_PROXY_WASM_BAD_VM_CLONE,
//    NGX_PROXY_WASM_MISSING_FUNCTION,
//    NGX_PROXY_WASM_BAD_INIT,
//    NGX_PROXY_WASM_START_FAILED,
//    NGX_PROXY_WASM_CONFIGURE_FAILED,
//    NGX_PROXY_WASM_RUNTIME_ERROR
//} ngx_proxy_wasm_fail_state;


typedef enum {
    NGX_PROXY_WASM_RES_OK = 0,
    NGX_PROXY_WASM_RES_EMPTY = 1,
    NGX_PROXY_WASM_RES_NOT_FOUND = 2,
    NGX_PROXY_WASM_RES_NOT_ALLOWED = 3,
    NGX_PROXY_WASM_RES_BAD_ARGUMENT = 4,
    NGX_PROXY_WASM_RES_BAD_MEM_ACCESS = 5,
    NGX_PROXY_WASM_RES_BAD_OPERATION = 6,
    NGX_PROXY_WASM_RES_CAS_MISMATCH = 7
} ngx_proxy_wasm_result;


typedef enum {
    NGX_PROXY_WASM_ACTION_CONTINUE = 1,
    NGX_PROXY_WASM_ACTION_END_STREAM = 2,
    NGX_PROXY_WASM_ACTION_DONE = 3,
    NGX_PROXY_WASM_ACTION_PAUSE = 4,
    NGX_PROXY_WASM_ACTION_WAIT = 5,
    NGX_PROXY_WASM_ACTION_WAIT_FULL = 6,
    NGX_PROXY_WASM_ACTION_CLOSE = 7
} ngx_proxy_wasm_action;


typedef enum {
    NGX_PROXY_WASM_LOG_TRACE = 1,
    NGX_PROXY_WASM_LOG_DEBUG = 2,
    NGX_PROXY_WASM_LOG_INFO = 3,
    NGX_PROXY_WASM_LOG_WARNING = 4,
    NGX_PROXY_WASM_LOG_ERROR = 5
} ngx_proxy_wasm_log_level;


typedef enum {
    NGX_PROXY_WASM_CONTEXT_VM = 1,
    NGX_PROXY_WASM_CONTEXT_PLUGIN = 2,
    NGX_PROXY_WASM_CONTEXT_STREAM = 3,
    NGX_PROXY_WASM_CONTEXT_HTTP = 4
} ngx_proxy_wasm_context;


typedef enum {
    NGX_PROXY_WASM_STREAM_TYPE_DOWNSTREAM = 1,
    NGX_PROXY_WASM_STREAM_TYPE_UPSTREAM = 2,
    NGX_PROXY_WASM_STREAM_TYPE_HTTP_REQUEST = 3,
    NGX_PROXY_WASM_STREAM_TYPE_HTTP_RESPONSE = 4
} ngx_proxy_wasm_stream_type;


typedef enum {
    NGX_PROXY_WASM_CLOSE_SOURCE_LOCAL = 1,
    NGX_PROXY_WASM_CLOSE_SOURCE_REMOTE = 2
} ngx_proxy_wasm_close_source_type;


typedef enum {
    NGX_PROXY_WASM_BUFFER_VM_CONFIGURATION = 1,
    NGX_PROXY_WASM_BUFFER_PLUGIN_CONFIGURATION = 2,
    NGX_PROXY_WASM_BUFFER_DOWNSTREAM_DATA = 3,
    NGX_PROXY_WASM_BUFFER_UPSTREAM_DATA = 4,
    NGX_PROXY_WASM_BUFFER_HTTP_REQUEST_BODY = 5,
    NGX_PROXY_WASM_BUFFER_HTTP_RESPONSE_BODY = 6,
    NGX_PROXY_WASM_BUFFER_HTTP_CALL_RESPONSE_BODY = 7
} ngx_proxy_wasm_buffer_type;


typedef enum {
    NGX_PROXY_WASM_MAP_HTTP_REQUEST_HEADERS = 1,
    NGX_PROXY_WASM_MAP_HTTP_REQUEST_TRAILERS = 2,
    NGX_PROXY_WASM_MAP_HTTP_REQUEST_METADATA = 3,
    NGX_PROXY_WASM_MAP_HTTP_RESPONSE_HEADERS = 4,
    NGX_PROXY_WASM_MAP_HTTP_RESPONSE_TRAILERS = 5,
    NGX_PROXY_WASM_MAP_HTTP_RESPONSE_METADATA = 6,
    NGX_PROXY_WASM_MAP_HTTP_CALL_RESPONSE_HEADERS = 7,
    NGX_PROXY_WASM_MAP_HTTP_CALL_RESPONSE_TRAILERS = 8,
    NGX_PROXY_WASM_MAP_HTTP_CALL_RESPONSE_METADATA = 9
} ngx_proxy_wasm_map_type;


typedef enum {
    NGX_PROXY_WASM_METRIC_COUNTER = 1,
    NGX_PROXY_WASM_METRIC_GAUGE = 2,
    NGX_PROXY_WASM_METRIC_HISTOGRAM = 3
} ngx_proxy_wasm_metric_type;


#endif /* _NGX_PROXY_WASM_H_INCLUDED_ */
