FROM amd64/ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        clang \
        gcc \
        curl

# Note: this image is also used for local CI runs
RUN apt-get install -y --no-install-recommends \
        libpcre3-dev \
        zlib1g-dev \
        clang-tools \
        valgrind \
        nodejs \
        gcovr \
        sudo \
        git
