FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./assets/ci/nginx.conf /etc/nginx/nginx.conf
COPY ./t/data/hostname_cert.pem /etc/nginx/hostname_cert.pem
COPY ./t/data/hostname_key.pem /etc/nginx/hostname_key.pem
