name: Large CI

on:
  #pull_request:
  #  branches: '**'
  schedule:
    - cron: '0 9 * * *' # 9am UTC, 2am PST
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-large:
    name: 'Unit'
    #if: ${{ false }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        label: [""]
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest]
        cc: [gcc-9]
        ngx: [1.25.1]
        runtime: [wasmtime, wasmer, v8]
        wasmtime: [12.0.1]
        wasmer: [3.1.1]
        v8: [11.4.183.23]
        debug: [debug, no_debug]
        hup: [hup, no_hup]
        module_type: [static, dynamic]
        include:
          # OpenResty + static ngx_wasm_module
          - label: dynamic_module
            os: ubuntu-latest
            cc: gcc-9
            openresty: 1.21.4.1
            runtime: wasmtime
            wasmtime: 12.0.1
            debug: debug
            hup: no_hup
            ssl: ssl
            module_type: static
    uses: ./.github/workflows/job-unit-tests.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      ngx: ${{ matrix.ngx }}
      openresty: ${{ matrix.openresty }}
      runtime: ${{ matrix.runtime }}
      wasmtime: ${{ matrix.wasmtime }}
      wasmer: ${{ matrix.wasmer }}
      v8: ${{ matrix.v8 }}
      ssl: ${{ matrix.ssl }}
      debug: ${{ matrix.debug }}
      hup: ${{ matrix.hup }}
      module_type: ${{ matrix.module_type }}

  valgrind-large:
    name: 'Valgrind'
    #if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        cc: [gcc-10]
        ngx: [1.25.1]
        runtime: [wasmer, wasmtime, v8]
        wasmtime: [12.0.1]
        wasmer: [3.1.1]
        v8: [11.4.183.23]
        hup: [hup, no_hup]
        debug: [debug]
        include:
          # OpenResty
          - label: openresty
            os: ubuntu-22.04
            cc: gcc-10
            openresty: 1.21.4.1
            runtime: wasmer
            wasmer: 3.1.1
            debug: debug
            hup: no_hup
    uses: ./.github/workflows/job-valgrind-tests.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      ngx: ${{ matrix.ngx }}
      openresty: ${{ matrix.openresty }}
      runtime: ${{ matrix.runtime }}
      wasmtime: ${{ matrix.wasmtime }}
      wasmer: ${{ matrix.wasmer }}
      v8: ${{ matrix.v8 }}
      hup: ${{ matrix.hup }}
      debug: ${{ matrix.debug }}
    secrets: inherit

  analyzer-large:
    name: 'Clang analyzer'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [clang-11]
        openresty: [1.21.4.1]
        runtime: [wasmtime, wasmer, v8]
        wasmtime: [12.0.1]
        wasmer: [3.1.1]
        v8: [11.4.183.23]
        ssl: [no_ssl, ssl]
        debug: [debug, no_debug]
    uses: ./.github/workflows/job-clang-analyzer.yml
    with:
      cc: ${{ matrix.cc }}
      ngx: ${{ matrix.ngx }}
      openresty: ${{ matrix.openresty }}
      runtime: ${{ matrix.runtime }}
      wasmtime: ${{ matrix.wasmtime }}
      wasmer: ${{ matrix.wasmer }}
      v8: ${{ matrix.v8 }}
      ssl: ${{ matrix.ssl }}
      debug: ${{ matrix.debug }}
