name: Large CI

on:
  schedule:
    - cron: '0 9 * * mon-fri' # 9am UTC, 2am PST

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: 'Tests - unit (large)'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      NGX_BUILD_FORCE: 1
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        #cc: [gcc-8, gcc-9, clang]
        cc: [clang]
        #ngx: [1.18.0, 1.19.1]
        ngx: [1.21.0]
        wasmtime: [0.25.0]
        #hup: [1, 0]
        hup: [0]
        #debug: [1, 0]
        debug: [1]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up cache - rustup toolchain"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.{yml,sh}') }}
      - name: "Set up cache - ngx_wasm_module work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        id: cache
        with:
          path: |
            work
            !work/scans
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Set up wasmtime
        uses: ./.github/actions/wasmtime
        with:
          version: ${{ matrix.wasmtime }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
          NGX_BUILD_DEBUG: ${{ matrix.debug }}
      - run: make test
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}

  build:
    name: 'Tests - build (large)'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [clang]
        ngx: [1.21.0]
        wasmtime: [0.27.0]
        runtime: [wasmtime]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up cache - ngx_wasm_module work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        id: cache
        with:
          path: |
            work
            !work/scans
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Set up wasmtime
        if: ${{ matrix.runtime == 'wasmtime' }}
        uses: ./.github/actions/wasmtime
        with:
          version: ${{ matrix.wasmtime }}
      - run: make setup
      - run: make test-build
        env:
          NGX_WASM_RUNTIME: ${{ matrix.runtime }}
