name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

env:
  TEST_NGINX_RANDOMIZE: 1

jobs:
  tests:
    name: 'Tests - unit'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      NGX_BUILD_GCOV: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [gcc-8]
        ngx: [1.21.6]
        runtime: [wasmer]
        wasmer: [2.1.1]
        hup: [0]
        debug: [1, 0]
        include:
          - os: ubuntu-latest
            ngx: 1.21.6
            runtime: wasmtime
            wasmtime: 0.36.0
            hup: 1
            debug: 1
    steps:
      - run: sudo apt-get update && sudo apt-get install -y gcc-8
        if: ${{ matrix.cc == 'gcc-8' }}
      - uses: actions/checkout@v2
      - name: "Setup cache - rustup toolchain"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.{yml,sh}') }}
      - name: "Setup cache - work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh,js}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Setup gcov
        if: ${{ !env.ACT && env.NGX_BUILD_GCOV }}
        run: sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/$(echo ${{ matrix.cc }} | sed s/gcc/gcov/) 100
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Setup Wasm runtime
        uses: ./.github/actions/wasm-runtime
        with:
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix[matrix.runtime] }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
          NGX_BUILD_DEBUG: ${{ matrix.debug }}
      - run: make test
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
      #- run: |
      #    pkill -9 nginx
      #    sleep 10
      #    tar -czf logs.tar.gz `find t/ -type f -name 'error.log'`
      #  if: ${{ failure() && !env.ACT }}
      #- uses: actions/upload-artifact@v2
      #  if: ${{ failure() && !env.ACT }}
      #  with:
      #    name: error_logs-${{ github.workflow }}-sha-${{ github.sha }}-run-${{ github.run_number }}
      #    path: error_logs.tar.gz
      - uses: codecov/codecov-action@v1
        if: ${{ !env.ACT }}
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit
          env_vars: TEST_NGINX_USE_HUP
          fail_ci_if_error: true

  valgrind:
    name: 'Tests - valgrind'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    #if: ${{ false }}
    env:
      NGX_BUILD_NOPOOL: 1
      NGX_BUILD_CC_OPT: '-O2'
      TEST_NGINX_TIMEOUT: 60
      TEST_NGINX_USE_VALGRIND: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [gcc-8]
        ngx: [1.21.6]
        runtime: [wasmer]
        wasmer: [2.1.1]
        hup: [0, 1]
        debug: [1]
    steps:
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - run: sudo apt-get install -y gcc-8
        if: ${{ matrix.cc == 'gcc-8' }}
      - uses: actions/checkout@v2
      - name: "Setup cache - rustup toolchain"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.{yml,sh}') }}
      - name: "Setup cache - work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh,js}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Setup Wasm runtime
        uses: ./.github/actions/wasm-runtime
        with:
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix[matrix.runtime] }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
          NGX_BUILD_DEBUG: ${{ matrix.debug }}
      - run: make test 2>&1 | tee valgrind.out
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
      - run: |
          awk -f ./util/parse-valgrind.awk valgrind.out > valgrind.log
          if [[ -s valgrind.log ]]; then
            cat valgrind.log >&2
            exit 1
          fi
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && !env.ACT }}
        with:
          name: gh-failures-${{ github.workflow }}-sha-${{ github.sha }}-run-${{ github.run_number }}
          path: valgrind.out

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    #if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh,js}') }}-${{ hashFiles('rust-toolchain') }}
      - run: make setup
      - run: make lint
      - uses: actions-rs/clippy-check@v1
        if: ${{ !env.ACT }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - run: |
          if [[ $(make reindex 2>&1 | tee reindex.out | grep -c done) -gt 0 ]]; then
            cat reindex.out >&2
            exit 1
          fi

  analyzer:
    name: 'Clang analyzer'
    runs-on: ubuntu-latest
    #if: ${{ false }}
    env:
      NGX_BUILD_CLANG_ANALYZER: 1
    strategy:
      fail-fast: false
      matrix:
        cc: [clang-9]
        ngx: [1.21.6]
        wasmtime: [0.36.0]
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y $(echo ${{ matrix.cc }} | sed s/clang/clang-tools/)
          sudo update-alternatives --install /usr/bin/scan-build scan-build /usr/bin/$(echo ${{ matrix.cc }} | sed s/clang/scan-build/) 100
      - uses: actions/checkout@v2
      - name: "Setup cache - work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh,js}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Setup Wasm runtime
        uses: ./.github/actions/wasm-runtime
        with:
          version: ${{ matrix.wasmtime }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && !env.ACT }}
        with:
          name: gh-failures-${{ github.workflow }}-sha-${{ github.sha }}-run-${{ github.run_number }}
          path: work/scans/*

  build:
    name: 'Tests - build'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    #if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [clang]
        ngx: [1.21.6]
        runtime: [wasmer, wasmtime]
        wasmtime: [0.36.0]
        wasmer: [2.1.1]
    steps:
      - uses: actions/checkout@v2
      - name: "Setup cache - work/ dir"
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('util/**/*.{sh,pl,awk}') }}-${{ hashFiles('.github/**/*.{yml,sh,js}') }}-${{ hashFiles('rust-toolchain') }}
      - name: Setup Wasm runtime
        uses: ./.github/actions/wasm-runtime
        with:
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix[matrix.runtime] }}
      - run: make setup
      - run: make test-build
        env:
          NGX_WASM_RUNTIME: ${{ matrix.runtime }}
