name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '**'

defaults:
  run:
    shell: bash

env:
  TEST_NGINX_RANDOMIZE: 1

jobs:
  tests:
    name: 'Tests - unit'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    #if: ${{ false }}
    outputs:
      coveralls_name: ${{ steps.lcov.outputs.name }}
    env:
      NGX_BUILD_GCOV: 1
      TEST_NGINX_TIMEOUT: 60
      TEST_NGINX_EXTERNAL_TIMEOUT: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [gcc-9]
        ngx: [1.23.4]
        runtime: [wasmer]
        wasmer: [3.1.1]
        ssl: [1]
        debug: [1, 0]
        hup: [0]
        include:
          # Wasmtime
          - os: ubuntu-latest
            cc: gcc-9
            ngx: 1.23.4
            runtime: wasmtime
            wasmtime: 7.0.0
            ssl: 1
            debug: 1
            hup: 1
          # V8
          - os: ubuntu-latest
            cc: gcc-9
            ngx: 1.23.4
            runtime: v8
            v8: 10.5.18
            ssl: 1
            debug: 1
            hup: 0
          # OpenResty
          - os: ubuntu-latest
            cc: gcc-9
            openresty: 1.21.4.1
            runtime: wasmtime
            wasmtime: 7.0.0
            ssl: 1
            debug: 1
            hup: 0
          # Old Nginx
          - os: ubuntu-latest
            cc: gcc-9
            ngx: 1.21.6
            runtime: wasmer
            wasmer: 3.1.1
            ssl: 1
            debug: 1
            hup: 0
          # No SSL
          - os: ubuntu-latest
            cc: gcc-9
            ngx: 1.23.4
            runtime: wasmer
            wasmer: 3.1.1
            ssl: 0
            debug: 0
            hup: 0
    steps:
      - name: 'Setup deps - apt-get'
        if: ${{ matrix.cc == 'gcc-9' }}
        run: sudo apt-get update && sudo apt-get install -y gcc-9 libstdc++-9-dev lcov
      - uses: actions/checkout@v3
      - name: 'Setup cache - rustup toolchain'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.yml', '.github/**/*.sh') }}
      - name: 'Setup cache - work/ dir'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ matrix.runtime }}-${{ hashFiles('util/**/*.sh', 'util/**/*.pl', 'util/**/*.awk', '.github/**/*.yml', '.github/**/*.sh', '.github/**/*.js', 'rust-toolchain') }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.25.0
      - name: Setup Wasm runtime
        run: ./util/runtime.sh -R ${{ matrix.runtime }} -V ${{ matrix[matrix.runtime] }}
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
          NGX_BUILD_SSL: ${{ matrix.ssl }}
          NGX_BUILD_DEBUG: ${{ matrix.debug }}
          NGX_BUILD_OPENRESTY: ${{ matrix.openresty }}
      - run: make test
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
      - name: Run lcov
        id: lcov
        if: ${{ !env.ACT && matrix.cc == 'gcc-9' }}
        run: |
          name="unit"
          if [ -n "${{ matrix.openresty }}" ]; then
            name="$name-openresty_${{ matrix.openresty }}"
          else
            name="$name-ngx_${{ matrix.ngx }}"
          fi
          name="$name-${{ matrix.runtime }}"
          name="$name-ssl_${{ matrix.ssl }}"
          name="$name-debug_${{ matrix.debug }}"
          name="$name-hup_${{ matrix.hup }}"
          echo "name=$name" >> $GITHUB_OUTPUT
          lcov --capture --directory work/buildroot --output-file lcov.info
          lcov --extract lcov.info "*/ngx_wasm_module/src/*" --output-file lcov.info
      - name: Coveralls Upload
        if: ${{ !env.ACT && matrix.cc == 'gcc-9' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ${{ steps.lcov.outputs.name }}
          path-to-lcov: './lcov.info'
          parallel: true
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && !env.ACT }}
        with:
          name: ${{ github.workflow }}-${{ github.job }}-sha-${{ github.sha }}-run-${{ github.run_number }}-${{ matrix.runtime }}
          path: |
            work/buildroot/
            t/servroot*

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
          carryforward: "unit-ngx_1.23.4-wasmer-ssl_1-debug_1-hup_0,unit-ngx_1.23.4-wasmer-ssl_1-debug_0-hup_0,unit-ngx_1.23.4-wasmtime-ssl_1-debug_1-hup_1,unit-ngx_1.23.4-v8-ssl_1-debug_1-hup_0,unit-openresty_1.21.4.1-wasmtime-ssl_1-debug_1-hup_0,unit-ngx_1.21.6-wasmer-ssl_1-debug_1-hup_0,unit-ngx_1.23.4-wasmer-ssl_0-debug_0-hup_0"

  valgrind:
    name: 'Tests - valgrind'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    #if: ${{ false }}
    env:
      NGX_BUILD_NOPOOL: 1
      NGX_BUILD_CC_OPT: '-O2'
      TEST_NGINX_TIMEOUT: 120
      TEST_NGINX_EXTERNAL_TIMEOUT: 200
      TEST_NGINX_USE_VALGRIND: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        cc: [gcc-10]
        ngx: [1.23.4]
        runtime: [wasmer]
        wasmer: [3.1.1]
        hup: [0, 1]
        debug: [1]
        include:
          # Wasmtime
          - os: ubuntu-22.04
            cc: gcc-10
            ngx: 1.23.4
            runtime: wasmtime
            wasmtime: 7.0.0
            hup: 0
            debug: 1
          # V8
          - os: ubuntu-22.04
            cc: gcc-10
            ngx: 1.23.4
            runtime: v8
            v8: 10.5.18
            hup: 0
            debug: 1
          # OpenResty
          - os: ubuntu-22.04
            cc: gcc-10
            ngx:
            openresty: 1.21.4.1
            runtime: wasmer
            wasmer: 3.1.1
            hup: 0
            debug: 1
    steps:
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - uses: actions/checkout@v3
      - name: 'Setup cache - rustup toolchain'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.yml', '.github/**/*.sh') }}
      - name: 'Setup cache - work/ dir'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ matrix.runtime }}-${{ hashFiles('util/**/*.sh', 'util/**/*.pl', 'util/**/*.awk', '.github/**/*.yml', '.github/**/*.sh', '.github/**/*.js', 'rust-toolchain') }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-wasi
      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.25.0
      - name: Setup Wasm runtime
        run: ./util/runtime.sh -R ${{ matrix.runtime }} -V ${{ matrix[matrix.runtime] }}
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
          NGX_BUILD_DEBUG: ${{ matrix.debug }}
          NGX_BUILD_OPENRESTY: ${{ matrix.openresty }}
      - run: make test 2>&1 | tee valgrind.out
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
          TEST_NGINX_NO_CLEAN: 1
      - run: |
          awk -f ./util/parse-valgrind.awk valgrind.out > valgrind.log
          if [[ -s valgrind.log ]]; then
            cat valgrind.log >&2
            exit 1
          fi
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && !env.ACT }}
        with:
          name: ${{ github.workflow }}-${{ github.job }}-sha-${{ github.sha }}-run-${{ github.run_number }}-${{ matrix.runtime }}
          path: |
            work/buildroot/
            t/servroot*
            valgrind.out

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    #if: ${{ false }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ matrix.runtime }}-${{ hashFiles('util/**/*.sh', 'util/**/*.pl', 'util/**/*.awk', '.github/**/*.yml', '.github/**/*.sh', '.github/**/*.js', 'rust-toolchain') }}
      - run: make setup
      - run: make lint
      - uses: actions-rs/clippy-check@v1
        if: ${{ !env.ACT }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - run: |
          if [[ $(make reindex 2>&1 | tee reindex.out | grep -c done) -gt 0 ]]; then
            cat reindex.out >&2
            exit 1
          fi

  analyzer:
    name: 'Clang analyzer'
    runs-on: ubuntu-latest
    #if: ${{ false }}
    env:
      NGX_BUILD_CLANG_ANALYZER: 1
    strategy:
      fail-fast: false
      matrix:
        cc: [clang-11]
        ngx: [1.23.4]
        runtime: [wasmtime]
        wasmtime: [7.0.0]
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y $(echo ${{ matrix.cc }} | sed s/clang/clang-tools/)
          sudo update-alternatives --install /usr/bin/scan-build scan-build /usr/bin/$(echo ${{ matrix.cc }} | sed s/clang/scan-build/) 100
      - uses: actions/checkout@v3
      - name: 'Setup cache - work/ dir'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ matrix.runtime }}-${{ hashFiles('util/**/*.sh', 'util/**/*.pl', 'util/**/*.awk', '.github/**/*.yml', '.github/**/*.sh', '.github/**/*.js', 'rust-toolchain') }}
      - name: Setup Wasm runtime
        run: ./util/runtime.sh -R ${{ matrix.runtime }} -V ${{ matrix[matrix.runtime] }}
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      - run: make setup
      - run: make
        env:
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.ngx }}
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && !env.ACT }}
        with:
          name: ${{ github.workflow }}-${{ github.job }}-sha-${{ github.sha }}-run-${{ github.run_number }}
          path: work/scans/*

  build:
    name: 'Tests - build'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    #if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: [clang-14, gcc-10]
        ngx: [1.23.4]
        runtime: [wasmer, wasmtime, v8]
        wasmtime: [7.0.0]
        wasmer: [3.1.1]
        v8: [10.5.18]
        include:
          - os: ubuntu-latest
            cc: clang-14
            ngx: 1.21.6
            runtime: wasmtime
            wasmtime: 7.0.0
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup cache - work/ dir'
        uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            work/downloads
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ matrix.runtime }}-${{ hashFiles('util/**/*.sh', 'util/**/*.pl', 'util/**/*.awk', '.github/**/*.yml', '.github/**/*.sh', '.github/**/*.js', 'rust-toolchain') }}
      - name: Setup Wasm runtime
        run: ./util/runtime.sh -R ${{ matrix.runtime }} -V ${{ matrix[matrix.runtime] }}
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      - run: make setup
      - run: make test-build
        env:
          NGX_WASM_RUNTIME: ${{ matrix.runtime }}
