name: Daily
on:
  schedule:
    - cron: '0 6 * * *' # daily, 6am
defaults:
  run:
    shell: bash

jobs:

  tests:
    name: 'Tests - unit (large)'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc-8, gcc-9, clang]
        nginx: [1.18.0, 1.19.1]
        wasmtime: [0.19.0]
        hup: [1, 0]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up cache - rustup toolchain"
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/*
            ~/.rustup/update-hashes/*
          key: rust-toolchain-${{ runner.os }}-${{ hashFiles('.github/**/*.{yml,sh}') }}
      - name: "Set up cache - ngx_wasm work/ dir"
        uses: actions/cache@v2
        id: cache
        with:
          path: work
          key: work-${{ runner.os }}-${{ matrix.cc }}-${{ matrix.ngx }}-${{ hashFiles('.github/**/*.{yml,sh}') }}
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: wasm32-unknown-unknown
          default: true
      - name: Set up wasmtime
        uses: ./.github/actions/wasmtime
        with:
          version: ${{ matrix.wasmtime }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: make setup
      - run: make
        env:
          NGX_BUILD_FORCE: 1
          CC: ${{ matrix.cc }}
          NGX: ${{ matrix.nginx }}
      - run: make test
        env:
          TEST_NGINX_USE_HUP: ${{ matrix.hup }}
