name: "Nightly release"
on:
  schedule:
    - cron: '30 23 * * *' # 11:30pm UTC

defaults:
  run:
    shell: bash

jobs:
  build-release:
    name: "Build release artifacts"
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
      NGX: 1.21.0
      WASMTIME: 0.27.0
      WASMER: 1.0.2
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: "Build release artifacts"
        run: |
          ./util/release.sh nightly-$(date -u +"%Y%m%d") --static --ngx ${{ env.NGX }} --wasmtime ${{ env.WASMTIME }} --wasmer ${{ env.WASMER }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist

  upload-release:
    name: "Upload release artifacts"
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve sibling release artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly"
          files: |
            *.tar.gz
