name: "Release"
on:
  schedule:
    - cron: '0 6 * * *' # 6am UTC, 11pm UTC-7
  workflow_dispatch:
    inputs:
        release_name:
          description: 'Release name (e.g. v0.1.0)'
          required: true
env:
  CC: clang
  NGX_VER: 1.21.0
  WASMTIME_VER: 0.27.0
  WASMER_VER: 1.0.2

defaults:
  run:
    shell: bash

jobs:
  build-images:
    name: "Build Docker images for binaries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Ubuntu 18.04 image"
        uses: docker/build-push-action@v2
        with:
          file: ./util/Dockerfiles/Dockerfile.amd64.ubuntu-18.04
          tags: wasmx-build-ubuntu:18.04
          push: true
      - name: "Archlinux image"
        uses: docker/build-push-action@v2
        with:
          file: ./util/Dockerfiles/Dockerfile.amd64.arch
          tags: wasmx-build-arch:latest
          push: true
      - if: ${{ !github.event.inputs.release_name }}
        run: echo "RELEASE_NAME=nightly-$(date -u +\"%Y%m%d\")" >> $GITHUB_ENV
      - if: ${{ github.event.inputs.release_name }}
        run: echo "RELEASE_NAME=${{ github.event.inputs.release_name }}" >> $GITHUB_ENV
      - name: "Build source release artifact"
        run: ./util/release.sh --src

  build-ubuntu-bionic:
    name: "Build Ubuntu 18.04 binary"
    needs: build-images
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/wasmx-build-ubuntu:18.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build binary
        run: ./util/release.sh --bin
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist

  build-arch:
    name: Build Archlinux binary
    needs: build-images
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/wasmx-build-ubuntu:18.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build binary
        run: ./util/release.sh --bin
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist

  build-macos:
    name: Build macOS binary
    needs: build-images
    runs-on: [macos-latest]
    steps:
      - name: Build binary
        run: ./util/release.sh --bin
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist

  upload-artifacts:
    name: Upload release artifacts
    needs: [build-ubuntu-bionic, build-arch, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve sibling release artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: release-${{ env.RELEASE_NAME }}
          prerelease: true
          title: ${{ env.RELEASE_NAME }}
          files: |
            *.tar.gz
